# Homework 1 - Introduction to Machine Learning

## Setup

In [24]:
import pandas as pd
import numpy as np
import wget

## Q1. Pandas version

In [2]:
pd.__version__

'3.0.6'

## Getting the data

In [11]:
wget.download('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

'car_fuel_efficiency_2026.csv'

In [12]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


## Q2. Records count

In [13]:
len(df)

10000

## Q3. Fuel types

In [14]:
df['fuel_type'].nunique()

3

## Q4. Missing values

In [15]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [16]:
(df.isnull().sum() > 0).sum()

np.int64(2)

## Q5. Max fuel efficiency

In [17]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

**Answer:** 41.2

## Q6. Median value of horsepower

In [20]:
median_before = df['horsepower'].median()
print('Median before filling:', median_before)

mode_hp = df['horsepower'].mode()[0]
print('Most frequent value (mode):', mode_hp)

horsepower_filled = df['horsepower'].fillna(mode_hp)
median_after = horsepower_filled.median()

print('Median after filling:', median_after)

Median before filling: 254.0
Most frequent value (mode): 252.0
Median after filling: 252.0


**Answer:** Yes, it decreased (from 254.0 to 252.0)

## Q7. Sum of weights

In [25]:
# Select Asia cars, columns vehicle_weight and model_year, first 7 rows
X_df = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7)
X_df

,vehicle_weight,model_year
2,4240,1996
6,4310,1992
8,4230,1997
10,4420,1978
15,3950,2007
16,4750,2021
22,4450,2019


In [26]:
# Get the underlying NumPy array
X = X_df.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [27]:
# Compute the matrix product of X transposed and X
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [28]:
# Invert the matrix XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [29]:
# 7: Create y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [30]:
# Compute the weights using the normal equation
w = XTX_inv.dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

In [31]:
# Sum of the weights
w.sum()

np.float64(0.36919696904925486)